export const SCREENING_CRITERIA_VERSION = 'fifa-gbi-full-text-v8-2026-06-23';

export const FULL_TEXT_SCREENING_CRITERIA = `
FIFA GBI full-text screening criteria:

Include studies that report original injury or illness epidemiology in FIFA-governed competitive association football, futsal, beach soccer, eligible para-football, or football referees/match officials, with football-specific data and a usable denominator such as exposure hours, player matches, match-exposures, athlete-exposures, a published study-specific time rate, or exact inputs for a defensible later derivation.

Do not exclude solely because an analysis is described as retrospective, or because data pass through a registry, insurance, league, or reporting database. Prospectively collected current-participant surveillance remains eligible when clubs, team medical staff, physicians, or equivalent competition reporters recorded injuries or illnesses prospectively and a registry, insurer, or league platform is only the reporting channel.

Published study-specific injury rates or incidence results can themselves supply the usable denominator frame even when the paper does not also print every raw exposure total. Do not misclassify league or MLS injury-surveillance papers as denominator failures when the paper reports football-specific rates from current-player surveillance.

Season-long club or team medical, dental, biomarker, or monitoring records from current players do not by themselves supply an eligible denominator. If a paper reports only player counts, injury counts, percentages, correlations, or associations without exposure hours, athlete-exposures, match-exposures, a published study-specific rate, or exact derivation inputs, exclude for no usable denominator rather than for retrospective/cross-sectional wording alone. Exclude direct football injury-specific, illness-specific, or case-only cohorts at full-text screening when they lack a usable at-risk denominator; do not keep them in stream for later no_exposure handling.

For injury and illness primary studies, player-seasons, athlete headcounts, follow-up seasons, and cumulative injury proportions do not replace exposure hours, athlete-exposures, match-exposures, a published study-specific time rate, or exact derivation inputs. If the paper states that precise exposure time was unavailable or that exposure data are needed to define incidence or burden, exclude for no usable denominator unless another accepted denominator is actually reported.

Treat paper-reported derivation inputs as usable only when they define the complete at-risk frame without extra assumptions. Examples include exact competition structure, completed repeated-surveillance observations, explicit athlete/player time units, a fully specified activity schedule, or a cohort mean exposure value multiplied by explicit participant count when the numerator is cohort-wide. Record the inputs later; do not calculate exposure during screening.

Do not treat a reported count of training sessions, matches, dataset rows, samples, or observations as athlete-exposures unless the paper explicitly establishes that each count is one athlete participating in one session or match and that the count is the complete unconditioned at-risk frame for the reported outcomes. A team-session count, an ambiguous session count, or conflicting row totals is not an athlete-exposure and cannot be repaired by assumption; exclude for no usable denominator when no other eligible denominator is reported.

Use slightly more leeway for football/soccer mental-health and psychological-health full texts because these studies are sparse. Direct quantitative participant-health outcome papers remain eligible when they report football-specific prevalence, counts, rates, burden, repeated measurements, or validated symptom scale results that can be extracted, even when the design is cross-sectional and the denominator is the responding football participant cohort. Do not use this leniency for attitude, awareness, perception, service-use, support, or broad wellness papers that do not report direct extractable participant-health outcomes.

Exclude wrong sport, competitions outside FIFA-governed football disciplines, non-competitive/recreational-only contexts that do not meet the project definition, records without football-specific subgroup data, records with counts or proportions but no usable denominator, public-source-only datasets such as Transfermarkt/public media datasets, hospital-record-only or claims-only datasets, registry/database studies whose underlying outcomes were not prospectively reported from current participating players/referees, purely biomechanical/performance/intervention papers without usable epidemiology, and retrospective/cross-sectional designs when they do not meet the current project policy.

If the available PDF or linked source is only a conference abstract, supplement abstract, or citation/abstract page rather than a real full text, exclude for Abstract instead of forcing another exclusion reason.

Retain relevant football-specific systematic reviews, scoping reviews, umbrella reviews, and meta-analyses for reference checking when they are likely to surface extraction-relevant primary studies on injury, illness, health-problem, or mental-health incidence, prevalence, burden, rates, denominators/exposure, surveillance, or comparable participant-health outcomes. These are not primary extraction studies, but the AI suggestion should be Include with a short review-route reason. Exclude narrative reviews, editorials, commentaries, protocols, generic football reviews, and reviews limited to prevention exercises, rehabilitation, return-to-play, performance tests, mechanisms, imaging, or proxy outcomes unless the review itself includes extractable football epidemiology/reference value.

Cited reviews, meta-analyses, or review language that appears only in background discussion, comparison text, or the reference list do not make the current paper a review. Judge review status from the paper's own study design, methods, and results, with priority on the title, abstract, and methods sections.

If the evidence is insufficient to decide, choose Exclude only when a concrete exclusion reason is supported by the text. Otherwise use the most conservative decision supported by the PDF and explain uncertainty in the reason.
`.trim();
