-- ============================================================================
-- SETUP PROFILE PASSWORDS (GENERATED)
-- ============================================================================
-- 
-- This script was generated by generate-profile-passwords.mjs
-- It updates the password_hash column in the profiles table for all profiles.
--
-- INSTRUCTIONS:
-- 1. Go to your Supabase Dashboard > SQL Editor
-- 2. Copy-paste this ENTIRE file
-- 3. Click "Run" (or press Cmd/Ctrl + Enter)
-- 4. Review the verification output at the end
--
-- SECURITY:
-- - Passwords are randomly generated (10 characters, secure format)
-- - Passwords are hashed using pgcrypto (bcrypt algorithm, 10 rounds)
-- - Plaintext passwords are stored in PROFILE_PASSWORDS.md
-- - Share passwords securely with each user individually
--
-- ============================================================================

-- Ensure pgcrypto extension is available
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- STEP 1: CREATE MIGRATION (if not already run)
-- ============================================================================

-- Add password_hash column to profiles table (if it doesn't exist)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'profiles' 
    AND column_name = 'password_hash'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN password_hash text;
    RAISE NOTICE 'Added password_hash column to profiles table';
  ELSE
    RAISE NOTICE 'password_hash column already exists';
  END IF;
END $$;

-- Add comment explaining the column
COMMENT ON COLUMN public.profiles.password_hash IS 'Bcrypt hash of the profile password. Used for password verification without requiring email-based auth.';

-- Create function to verify profile password (if it doesn't exist)
CREATE OR REPLACE FUNCTION public.verify_profile_password(
  profile_id uuid,
  provided_password text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  stored_hash text;
BEGIN
  -- Get the stored password hash for the profile
  SELECT password_hash INTO stored_hash
  FROM public.profiles
  WHERE id = profile_id;

  -- If no hash exists, return false
  IF stored_hash IS NULL THEN
    RETURN false;
  END IF;

  -- Verify the password using crypt function
  -- crypt(provided_password, stored_hash) will use the salt from stored_hash
  -- and return the same hash if password matches
  RETURN crypt(provided_password, stored_hash) = stored_hash;
END;
$$;

COMMENT ON FUNCTION public.verify_profile_password IS 'Verifies a password against a profile''s stored password hash using bcrypt.';

-- ============================================================================
-- UPDATE PROFILE PASSWORDS
-- ============================================================================

-- AbdelRahman Babiker (admin)
UPDATE public.profiles
SET password_hash = crypt('TD7S#hxUNn', gen_salt('bf', 10)),
    updated_at = now()
WHERE id = '00000000-0000-0000-0000-000000000001';

-- Ayman (extractor)
UPDATE public.profiles
SET password_hash = crypt('VM!sP&wf4T', gen_salt('bf', 10)),
    updated_at = now()
WHERE id = '00000000-0000-0000-0000-000000000004';

-- Dr. Amr Alkhotany (extractor)
UPDATE public.profiles
SET password_hash = crypt('2nthW3Uu&D', gen_salt('bf', 10)),
    updated_at = now()
WHERE id = '00000000-0000-0000-0000-000000000002';

-- Dr. Ben Clarsen (extractor)
UPDATE public.profiles
SET password_hash = crypt('SvLG#R678L', gen_salt('bf', 10)),
    updated_at = now()
WHERE id = '550e8400-e29b-41d4-a716-446655440001';

-- Dr. Nicol van Dyk (extractor)
UPDATE public.profiles
SET password_hash = crypt('*5G%JRi!4u', gen_salt('bf', 10)),
    updated_at = now()
WHERE id = '550e8400-e29b-41d4-a716-446655440003';

-- Jamal (extractor)
UPDATE public.profiles
SET password_hash = crypt('*3M4pY2pEV', gen_salt('bf', 10)),
    updated_at = now()
WHERE id = '00000000-0000-0000-0000-000000000003';

-- Professor Eamonn Delahunt (extractor)
UPDATE public.profiles
SET password_hash = crypt('YtbeXh&xP9', gen_salt('bf', 10)),
    updated_at = now()
WHERE id = '550e8400-e29b-41d4-a716-446655440002';

-- Sadeer Rami (extractor)
UPDATE public.profiles
SET password_hash = crypt('*3#nPzGC@s', gen_salt('bf', 10)),
    updated_at = now()
WHERE id = '00000000-0000-0000-0000-000000000005';

-- Time Observer (observer)
UPDATE public.profiles
SET password_hash = crypt('!r@#yU%d5V', gen_salt('bf', 10)),
    updated_at = now()
WHERE id = '00000000-0000-0000-0000-000000000006';

-- ============================================================================
-- VERIFICATION
-- ============================================================================

-- Show all profiles with password status
SELECT 
  id,
  full_name,
  role,
  CASE 
    WHEN password_hash IS NOT NULL AND password_hash != '' THEN '✅ Password set'
    ELSE '❌ No password'
  END as password_status
FROM public.profiles
ORDER BY full_name;

-- ============================================================================
